apiVersion: v1
kind: Secret
metadata:
  name: pay-db-secret
  namespace: pairmate-prod
type: Opaque
data:
  DB_USERNAME: cGF5ZGJ1c2VybmFtZXByb2Q=
  DB_PASSWORD: cGF5ZGJwYXNzd29yZHByb2Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: pay-db-secret
  namespace: pairmate-test
type: Opaque
data:
  DB_USERNAME: cGF5ZGJ1c2VybmFtZXRlc3Q=
  DB_PASSWORD: cGF5ZGJwYXNzd29yZHRlc3Q=