apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: pairmate-prod
type: Opaque
data:
  DB_USERNAME: dXNlcmRidXNlcm5hbWVwcm9k
  DB_PASSWORD: dXNlcmRicGFzc3dvcmRwcm9k
---
apiVersion: v1
kind: Secret
metadata:
  name: user-db-secret
  namespace: pairmate-test
type: Opaque
data:
  DB_USERNAME: dXNlcmRidXNlcm5hbWV0ZXN0
  DB_PASSWORD: dXNlcmRicGFzc3dvcmR0ZXN0