server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      config:
        uri: http://config-server:8888
      eureka:
        client:
          service-url:
            defaultZone: http://eureka-server:8761/eureka/
      routes:
        # User Service
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**

        # Pay Service
        - id: pay-service
          uri: http://pay-service:8082
          predicates:
            - Path=/payments/**

        # Review Service
        - id: review-service
          uri: http://review-service:8083
          predicates:
            - Path=/reviews/**

        # Store Service
        - id: store-service
          uri: http://store-service:8084
          predicates:
            - Path=/stores/**

        # Event Service
        - id: event-service
          uri: http://event-service:8085
          predicates:
            - Path=/events/**
