version: "3.8"

services:
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=git
    networks:
      - pairmate-net

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - pairmate-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8080"
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - pairmate-net

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
      - user-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    networks:
      - pairmate-net

networks:
  pairmate-net:
    driver: bridge
