apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: pairmate-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: frontend
          image: kr.ncr.ntruss.com/pairmate-registry/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          # Nginx 기본 경로
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: pairmate-prod
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP