######################################
# PROD 환경
######################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: pairmate-prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend
          image: jiwonlee42/frontendservice:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "192Mi"
          envFrom:
            - secretRef:
                name: frontend-secret
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: pairmate-prod
spec:
  selector:
    app: frontend-service
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP