######################################
#  TEST 환경 - USER DB
######################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-pvc
  namespace: pairmate-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nks-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: pairmate-test
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: [ 'sh', '-c', 'chmod -R 777 /var/lib/mysql' ]
          volumeMounts:
            - name: user-db-storage
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: userdb
            - name: TZ
              value: "Asia/Seoul"
            - name: MYSQL_ROOT_HOST
              value: "%"
          command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
          volumeMounts:
            - name: user-db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: user-db-storage
          persistentVolumeClaim:
            claimName: user-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: pairmate-test
spec:
  selector:
    app: user-db
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None
---
######################################
#  PROD 환경 - USER DB
######################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-pvc
  namespace: pairmate-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: pairmate-prod
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: [ 'sh', '-c', 'chmod -R 777 /var/lib/mysql' ]
          volumeMounts:
            - name: user-db-storage
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: userdb
            - name: TZ
              value: "Asia/Seoul"
            - name: MYSQL_ROOT_HOST
              value: "%"
          command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
          volumeMounts:
            - name: user-db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: user-db-storage
          persistentVolumeClaim:
            claimName: user-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: pairmate-prod
spec:
  selector:
    app: user-db
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None