######################################
# USER DB (PROD)
######################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
  namespace: pairmate-prod
spec:
  serviceName: user-db
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: userdb
          volumeMounts:
            - name: user-db-storage
              mountPath: /var/lib/mysql
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: init-db
          configMap:
            name: user-db-init-config
  volumeClaimTemplates:
    - metadata:
        name: user-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 8Gi
        storageClassName: nks-block-storage
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: pairmate-prod
spec:
  type: ClusterIP
  selector:
    app: user-db
  ports:
    - port: 3306
      targetPort: 3306