apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: pairmate-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: config-server
          image: kr.ncr.ntruss.com/pairmate-registry/config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: GIT_URI
              valueFrom:
                secretKeyRef:
                  name: config-git-secret
                  key: GIT_URI
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-git-secret
                  key: GIT_USERNAME
            - name: GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-git-secret
                  key: GIT_PASSWORD
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            failureThreshold: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: pairmate-prod
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
  type: ClusterIP