apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: pairmate-prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      imagePullSecrets:
        - name: ncr-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: eureka-server
      # config 실행 대기
      initContainers:
        - name: wait-for-config
          image: busybox
          command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting config; sleep 3; done;']
      containers:
        - name: eureka-server
          image: pairmate-registry.kr.ncr.ntruss.com/eureka-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          envFrom:
            - configMapRef:
                name: global-config
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            failureThreshold: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8761
              path: /actuator/health/readiness
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: pairmate-prod
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP