apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: pairmate-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      imagePullSecrets:
        - name: ncr-secret
      # eureka, config 대기
      initContainers:
        - name: wait-for-config
          image: busybox
          command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting config; sleep 3; done;']
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting eureka; sleep 3; done;']
      containers:
        - name: gateway-service
          image: pairmate-registry.kr.ncr.ntruss.com/gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: global-config
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 50
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: pairmate-prod
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: pairmate-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      imagePullSecrets:
        - name: ncr-secret
      # eureka, config 대기
      initContainers:
        - name: wait-for-config
          image: busybox
          command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting config; sleep 3; done;']
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting eureka; sleep 3; done;']
      containers:
        - name: gateway-service
          image: pairmate-registry.kr.ncr.ntruss.com/gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: global-config
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 50
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: pairmate-test
spec:
  selector:
    app: gateway-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
