apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-service
  namespace: pairmate-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pay-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: pay-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      initContainers:
        # Config Server, Eureka, DB가 준비될 때까지 대기
        - name: wait-for-config
          image: busybox
          command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting config; sleep 3; done;']
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting eureka; sleep 3; done;']
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z user-db 3306; do echo waiting db; sleep 3; done;']

      containers:
        - name: pay-service
          image: docker.io/jiwonlee42/pay-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          envFrom:
            - configMapRef:
                name: global-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-secret
                  key: DB_PASSWORD
#            - name: PG_API_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: pay-pg-secret
#                  key: PG_API_KEY
#            - name: PG_SECRET
#              valueFrom:
#                secretKeyRef:
#                  name: pay-pg-secret
#                  key: PG_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 5

          # 활성 상태 프로브 (프로세스 응답 확인)
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: pay-service
  namespace: pairmate-prod
spec:
  selector:
    app: pay-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
