# ================================
# store-service (pairmate-prod)
# ================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-service
  namespace: pairmate-prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: store-service
  template:
    metadata:
      labels:
        app: store-service
    spec:
      initContainers:
        - name: wait-for-config
          image: busybox
          command: ['sh', '-c', 'until nc -z config-server 8888; do echo waiting config; sleep 3; done;']
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z eureka-server 8761; do echo waiting eureka; sleep 3; done;']
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z user-db 3306; do echo waiting db; sleep 3; done;']

      containers:
        - name: store-service
          image: docker.io/jiwonlee42/store-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          ports:
            - containerPort: 8082

          envFrom:
            - configMapRef:
                name: global-config

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: store-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: store-db-secret
                  key: DB_PASSWORD

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 150
            periodSeconds: 20
            timeoutSeconds: 20
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 20
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: store-service
  namespace: pairmate-prod
spec:
  selector:
    app: store-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP