apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: pairmate-prod
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      # Vite 빌드 결과물 경로
      root /usr/share/nginx/html;
      index index.html;

      # 정적 파일 직접 서빙
      location /assets/ {
          access_log off;
          expires 30d;
          add_header Cache-Control "public, no-transform";
          try_files $uri =404;
      }

      # API 요청은 Gateway로 전달
      location /api {
          proxy_pass http://gateway-service:8080;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_connect_timeout 10s;
          proxy_read_timeout 60s;
      }

      # SPA fallback (React Router 등)
      location / {
          try_files $uri $uri/ /index.html;
      }

      # Gzip 압축 설정
      gzip on;
      gzip_vary on;
      gzip_min_length 1024;
      gzip_proxied any;
      gzip_types
          text/plain
          text/css
          application/json
          application/javascript
          application/x-javascript
          text/xml
          application/xml
          application/xml+rss
          image/svg+xml;
    }