apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: pairmate-prod
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        root /;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
      }

      # 모든 /api 요청은 Gateway로 프록시
      location /api {
        proxy_pass http://gateway-service:8080;
      }
    }