apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: pairmate-prod
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /app/dist;
      index index.html;

      # 정적 파일 직접 서빙
      location /assets/ {
          try_files $uri =404;
      }

      # API 요청은 Gateway로 전달
      location /api {
          proxy_pass http://gateway-service:8080;
      }

      # SPA fallback (React Router 등)
      location / {
          try_files $uri $uri/ /index.html;
      }

      gzip on;
      gzip_types text/plain application/javascript text/css application/json image/svg+xml;
    }
