server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PairMate/config-repo
          # default-label: main
          default-label: main
          search-paths:
            - .
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}