server:
  port: 8084
spring:
  application:
    name: review-service
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true   # 실패 시 바로 예외
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/